### ISSUE TITLE
ERD Drawing

### ISSUE THREAD

**Issue by MSmit99** [Etown-CS310/club_hub#25]

**Comment by muzzy3k** [comment]
updated on commit [86da7be1d38e68e7d974f102e98f75b18809ae50](https://github.com/Etown-CS310/club_hub/commit/86da7be1d38e68e7d974f102e98f75b18809ae50) [erd](https://github.com/Etown-CS310/club_hub/blob/86da7be1d38e68e7d974f102e98f75b18809ae50/images/mock_erd_model.png)
