### ISSUE TITLE
Weekly Report 10/13/2024

### ISSUE THREAD

**Issue by muzzy3k** [Etown-CS310/club_hub#4]

**Comment by muzzy3k** [comment]
#11 updated user settings.
#10 updated upcoming events to pull dynamically from database

**Comment by muzzy3k** [comment]
#12 added this feature on homepage

**Comment by JingwenJessica** [comment]
@MSmit99 Don't forget to update the weekly status report here.

**Comment by JingwenJessica** [comment]
> #11 updated user settings. #10 updated upcoming events to pull dynamically from database

Good job! These issues can be closed if they are completed.
